In [1]:
import pandas as pd

data1 = pd.read_csv('C:/Users/ASUS/Downloads/project/python-rescue-station/data/csv/network_distance.csv')
# data1.head(6)
data1

      StartPoint  EndPoint  Distance  net_length
0             49        50      10.0       510.0
1             50        51      10.0         0.0
2             51        52      10.0         0.0
3             52        53      10.0         0.0
4             53        54      10.0         0.0
...          ...       ...       ...         ...
2597          99        95      40.0         0.0
2598          99        96      30.0         0.0
2599          99        97      20.0         0.0
2600          99        98      10.0         0.0
2601          99       100      10.0         0.0

[2602 rows x 4 columns]

In [2]:
# Lấy các giá trị duy nhất từ cột 'StartPoint'
unique_destinations = set(data1['StartPoint'])

# In ra các giá trị duy nhất dưới dạng DataFrame
unique_destinations_df = pd.DataFrame({'StartPoint': list(unique_destinations)})
print(unique_destinations_df)

    StartPoint
0           49
1           50
2           51
3           52
4           53
5           54
6           55
7           56
8           57
9           58
10          59
11          60
12          61
13          62
14          63
15          64
16          65
17          66
18          67
19          68
20          69
21          70
22          71
23          72
24          73
25          74
26          75
27          76
28          77
29          78
30          79
31          80
32          81
33          82
34          83
35          84
36          85
37          86
38          87
39          88
40          89
41          90
42          91
43          92
44          93
45          94
46          95
47          96
48          97
49          98
50          99

In [3]:
data2 = pd.read_csv('C:/Users/ASUS/Downloads/project/python-rescue-station/data/csv/Thuyhe_Diemven2_84.csv')
# data2.head(6)
data2

        Id             XX            YY
0        0  612684.883012  1.189163e+06
1        1  612684.883012  1.189173e+06
2        2  612684.883012  1.189183e+06
3        3  612684.883012  1.189193e+06
4        4  612684.883012  1.189203e+06
...    ...            ...           ...
9841  9841  618633.328360  1.197564e+06
9842  9842  618630.751070  1.197554e+06
9843  9843  618628.184968  1.197544e+06
9844  9844  618625.906735  1.197535e+06
9845  9845  618624.740200  1.197530e+06

[9846 rows x 3 columns]

In [4]:
# Gộp hai DataFrame dựa trên cột 'Id' và chỉ lấy cột 'name' từ unique_destinations_df
merged_df = pd.merge(unique_destinations_df, data2[['Id', 'XX', 'YY']], left_on='StartPoint', right_on='Id')

# In ra kết quả
print(merged_df)

    StartPoint  Id             XX            YY
0           49  49  612711.842339  1.189633e+06
1           50  50  612721.419317  1.189635e+06
2           51  51  612730.996295  1.189638e+06
3           52  52  612740.573272  1.189641e+06
4           53  53  612750.150250  1.189644e+06
5           54  54  612759.727228  1.189647e+06
6           55  55  612769.304206  1.189650e+06
7           56  56  612778.881183  1.189653e+06
8           57  57  612788.458161  1.189656e+06
9           58  58  612798.035139  1.189659e+06
10          59  59  612807.612117  1.189661e+06
11          60  60  612817.189095  1.189664e+06
12          61  61  612826.766072  1.189667e+06
13          62  62  612836.343050  1.189670e+06
14          63  63  612845.920028  1.189673e+06
15          64  64  612855.497006  1.189676e+06
16          65  65  612865.073983  1.189679e+06
17          66  66  612874.650961  1.189682e+06
18          67  67  612884.227939  1.189684e+06
19          68  68  612893.804917  1.189687e+06
20          69  69  612903.381894  1.189690e+06
21          70  70  612912.958872  1.189693e+06
22          71  71  612922.535850  1.189696e+06
23          72  72  612932.112828  1.189699e+06
24          73  73  612941.689805  1.189702e+06
25          74  74  612951.266783  1.189705e+06
26          75  75  612960.843761  1.189707e+06
27          76  76  612970.420739  1.189710e+06
28          77  77  612979.997717  1.189713e+06
29          78  78  612989.574694  1.189716e+06
30          79  79  612999.151672  1.189719e+06
31          80  80  613008.728650  1.189722e+06
32          81  81  613018.305628  1.189725e+06
33          82  82  613027.882605  1.189728e+06
34          83  83  613037.459583  1.189730e+06
35          84  84  613047.042824  1.189733e+06
36          85  85  613056.770597  1.189736e+06
37          86  86  613066.498369  1.189738e+06
38          87  87  613076.226142  1.189740e+06
39          88  88  613085.953915  1.189743e+06
40          89  89  613095.681688  1.189745e+06
41          90  90  613105.409461  1.189747e+06
42          91  91  613115.137233  1.189750e+06
43          92  92  613124.865006  1.189752e+06
44          93  93  613134.592779  1.189754e+06
45          94  94  613144.320552  1.189756e+06
46          95  95  613154.048325  1.189759e+06
47          96  96  613163.776097  1.189761e+06
48          97  97  613173.503870  1.189763e+06
49          98  98  613183.231643  1.189766e+06
50          99  99  613192.959416  1.189768e+06

In [5]:
# Sắp xếp lại các cột theo thứ tự chieudai, frompoint, topoint
df_sorted = merged_df[['Id', 'StartPoint', 'XX', 'YY']]

print(df_sorted)

    Id  StartPoint             XX            YY
0   49          49  612711.842339  1.189633e+06
1   50          50  612721.419317  1.189635e+06
2   51          51  612730.996295  1.189638e+06
3   52          52  612740.573272  1.189641e+06
4   53          53  612750.150250  1.189644e+06
5   54          54  612759.727228  1.189647e+06
6   55          55  612769.304206  1.189650e+06
7   56          56  612778.881183  1.189653e+06
8   57          57  612788.458161  1.189656e+06
9   58          58  612798.035139  1.189659e+06
10  59          59  612807.612117  1.189661e+06
11  60          60  612817.189095  1.189664e+06
12  61          61  612826.766072  1.189667e+06
13  62          62  612836.343050  1.189670e+06
14  63          63  612845.920028  1.189673e+06
15  64          64  612855.497006  1.189676e+06
16  65          65  612865.073983  1.189679e+06
17  66          66  612874.650961  1.189682e+06
18  67          67  612884.227939  1.189684e+06
19  68          68  612893.804917  1.189687e+06
20  69          69  612903.381894  1.189690e+06
21  70          70  612912.958872  1.189693e+06
22  71          71  612922.535850  1.189696e+06
23  72          72  612932.112828  1.189699e+06
24  73          73  612941.689805  1.189702e+06
25  74          74  612951.266783  1.189705e+06
26  75          75  612960.843761  1.189707e+06
27  76          76  612970.420739  1.189710e+06
28  77          77  612979.997717  1.189713e+06
29  78          78  612989.574694  1.189716e+06
30  79          79  612999.151672  1.189719e+06
31  80          80  613008.728650  1.189722e+06
32  81          81  613018.305628  1.189725e+06
33  82          82  613027.882605  1.189728e+06
34  83          83  613037.459583  1.189730e+06
35  84          84  613047.042824  1.189733e+06
36  85          85  613056.770597  1.189736e+06
37  86          86  613066.498369  1.189738e+06
38  87          87  613076.226142  1.189740e+06
39  88          88  613085.953915  1.189743e+06
40  89          89  613095.681688  1.189745e+06
41  90          90  613105.409461  1.189747e+06
42  91          91  613115.137233  1.189750e+06
43  92          92  613124.865006  1.189752e+06
44  93          93  613134.592779  1.189754e+06
45  94          94  613144.320552  1.189756e+06
46  95          95  613154.048325  1.189759e+06
47  96          96  613163.776097  1.189761e+06
48  97          97  613173.503870  1.189763e+06
49  98          98  613183.231643  1.189766e+06
50  99          99  613192.959416  1.189768e+06

In [6]:
# # Đổi tên các cột
df = df_sorted.rename(columns={"StartPoint": "FacilityPoints"})
print(df)

    Id  FacilityPoints             XX            YY
0   49              49  612711.842339  1.189633e+06
1   50              50  612721.419317  1.189635e+06
2   51              51  612730.996295  1.189638e+06
3   52              52  612740.573272  1.189641e+06
4   53              53  612750.150250  1.189644e+06
5   54              54  612759.727228  1.189647e+06
6   55              55  612769.304206  1.189650e+06
7   56              56  612778.881183  1.189653e+06
8   57              57  612788.458161  1.189656e+06
9   58              58  612798.035139  1.189659e+06
10  59              59  612807.612117  1.189661e+06
11  60              60  612817.189095  1.189664e+06
12  61              61  612826.766072  1.189667e+06
13  62              62  612836.343050  1.189670e+06
14  63              63  612845.920028  1.189673e+06
15  64              64  612855.497006  1.189676e+06
16  65              65  612865.073983  1.189679e+06
17  66              66  612874.650961  1.189682e+06
18  67              67  612884.227939  1.189684e+06
19  68              68  612893.804917  1.189687e+06
20  69              69  612903.381894  1.189690e+06
21  70              70  612912.958872  1.189693e+06
22  71              71  612922.535850  1.189696e+06
23  72              72  612932.112828  1.189699e+06
24  73              73  612941.689805  1.189702e+06
25  74              74  612951.266783  1.189705e+06
26  75              75  612960.843761  1.189707e+06
27  76              76  612970.420739  1.189710e+06
28  77              77  612979.997717  1.189713e+06
29  78              78  612989.574694  1.189716e+06
30  79              79  612999.151672  1.189719e+06
31  80              80  613008.728650  1.189722e+06
32  81              81  613018.305628  1.189725e+06
33  82              82  613027.882605  1.189728e+06
34  83              83  613037.459583  1.189730e+06
35  84              84  613047.042824  1.189733e+06
36  85              85  613056.770597  1.189736e+06
37  86              86  613066.498369  1.189738e+06
38  87              87  613076.226142  1.189740e+06
39  88              88  613085.953915  1.189743e+06
40  89              89  613095.681688  1.189745e+06
41  90              90  613105.409461  1.189747e+06
42  91              91  613115.137233  1.189750e+06
43  92              92  613124.865006  1.189752e+06
44  93              93  613134.592779  1.189754e+06
45  94              94  613144.320552  1.189756e+06
46  95              95  613154.048325  1.189759e+06
47  96              96  613163.776097  1.189761e+06
48  97              97  613173.503870  1.189763e+06
49  98              98  613183.231643  1.189766e+06
50  99              99  613192.959416  1.189768e+06

In [7]:
import os

# Đường dẫn đến thư mục
folder_path = r'C:/Users/ASUS/Downloads/project/python-rescue-station/data/csv'

# Kiểm tra nếu thư mục không tồn tại, tạo mới
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Tạo đường dẫn đến file CSV trong thư mục
file_path = os.path.join(folder_path, 'facility_points.csv')

# Lưu dataframe thành file CSV
df.to_csv(file_path, index=False)

# Hiển thị kết quả
print("File CSV đã được lưu thành công vào thư mục:", folder_path)

File CSV đã được lưu thành công vào thư mục: C:/Users/ASUS/Downloads/project/python-rescue-station/data/csv