In [68]:
import pandas as pd

data = pd.read_csv('C:/Users/ASUS/Downloads/rescue_station_project/scripts/test_demo/csv/Thuyhe_HCM_motphan_test_graph.csv')
# data.head(6)
data

    FID_Thuyhe  Id  FromPoint  ToPoint  chieudai
0            1   1          1        2         9
1            1   2          2        3        13
2            1   3          3        4         8
3            1   4          4        5        13
4            1   5          5        6         9
5            1   6          1        3        12
6            1   7          1        4        10
7            1   8          2        5        17
8            1   9          3        5         7
9            1  10          4        6         7
10           1  11          1        7        25
11           1  12          4        8        13
12           1  13          4        9        20
13           1  14          4       11        15
14           1  15          4       15        30
15           1  16          6       19         6
16           1  17          7        8        10
17           1  18          7       10        10
18           1  19          7       14        20
19           1  20          9       10        15
20           1  21          9       13        10
21           1  22         10       14        25
22           1  23         11       12         8
23           1  24         11       15         7
24           1  25         11       17        20
25           1  26         12       13         6
26           1  27         12       16        10
27           1  28         12       17         6
28           1  29         15       18        25
29           1  30         15       19         8
30           1  31         16       18         7
31           1  32         17       18         6
32           1  33         18       20        30
33           1  34         19       20        10

In [69]:
# # Lấy 5 hàng đầu tiên
# df_first_5_rows = data.iloc[:5]

# # Hiển thị kết quả
# print(df_first_5_rows)

In [70]:
# Chọn cột và sắp xếp lại thứ tự cột
df_selected = data[['Id', 'FromPoint', 'ToPoint', 'chieudai']]

# Hiển thị kết quả
print(df_selected)

    Id  FromPoint  ToPoint  chieudai
0    1          1        2         9
1    2          2        3        13
2    3          3        4         8
3    4          4        5        13
4    5          5        6         9
5    6          1        3        12
6    7          1        4        10
7    8          2        5        17
8    9          3        5         7
9   10          4        6         7
10  11          1        7        25
11  12          4        8        13
12  13          4        9        20
13  14          4       11        15
14  15          4       15        30
15  16          6       19         6
16  17          7        8        10
17  18          7       10        10
18  19          7       14        20
19  20          9       10        15
20  21          9       13        10
21  22         10       14        25
22  23         11       12         8
23  24         11       15         7
24  25         11       17        20
25  26         12       13         6
26  27         12       16        10
27  28         12       17         6
28  29         15       18        25
29  30         15       19         8
30  31         16       18         7
31  32         17       18         6
32  33         18       20        30
33  34         19       20        10

In [71]:
# Nhập id x và id y từ người dùng
x = int(input("Nhập id x: "))
y = int(input("Nhập id y: "))

# Lọc ra các dòng có Id nằm trong khoảng từ id x đến id y
filtered_df = df_selected[(df_selected['Id'] >= x) & (df_selected['Id'] <= y)]

# In ra DataFrame mới
print(filtered_df)

    Id  FromPoint  ToPoint  chieudai
0    1          1        2         9
1    2          2        3        13
2    3          3        4         8
3    4          4        5        13
4    5          5        6         9
5    6          1        3        12
6    7          1        4        10
7    8          2        5        17
8    9          3        5         7
9   10          4        6         7
10  11          1        7        25
11  12          4        8        13
12  13          4        9        20
13  14          4       11        15
14  15          4       15        30
15  16          6       19         6
16  17          7        8        10
17  18          7       10        10
18  19          7       14        20
19  20          9       10        15
20  21          9       13        10
21  22         10       14        25
22  23         11       12         8
23  24         11       15         7
24  25         11       17        20
25  26         12       13         6
26  27         12       16        10
27  28         12       17         6
28  29         15       18        25
29  30         15       19         8
30  31         16       18         7
31  32         17       18         6
32  33         18       20        30
33  34         19       20        10

In [72]:
import networkx as nx

# Tạo đồ thị vô hướng từ dữ liệu filtered_df
G = nx.Graph()

# Thêm các cạnh vào đồ thị với trọng số tương ứng là 'chieudai'
for index, row in filtered_df.iterrows():
    G.add_edge(row['FromPoint'], row['ToPoint'], weight=row['chieudai'])

# Hàm tính khoảng cách network giữa các cặp đỉnh
def calculate_network_distances(graph):
    distances = dict(nx.all_pairs_dijkstra_path_length(graph, weight='weight'))
    return distances

# Tính toán khoảng cách
network_distances = calculate_network_distances(G)

# Chuyển đổi kết quả thành DataFrame
distance_records = []
for start_point, end_points in network_distances.items():
    for end_point, distance in end_points.items():
        distance_records.append({
            'FromPoint': start_point,
            'ToPoint': end_point,
            'chieudai': distance
        })

distance_df = pd.DataFrame(distance_records)

# Hiển thị DataFrame kết quả
print(distance_df)

     FromPoint  ToPoint  chieudai
0            1        1         0
1            1        2         9
2            1        4        10
3            1        3        12
4            1        6        17
..         ...      ...       ...
395         20        2        42
396         20        9        43
397         20        7        46
398         20       10        56
399         20       14        66

[400 rows x 3 columns]

In [73]:
# Trộn các kết quả vào chung 3 cột chieudai, FromPoint, ToPoint
merged_df = pd.concat([distance_df, filtered_df[['FromPoint', 'ToPoint', 'chieudai']]])

# Reset index để tránh index trùng lặp
merged_df.reset_index(drop=True, inplace=True)

# Hiển thị kết quả
print(merged_df)

     FromPoint  ToPoint  chieudai
0            1        1         0
1            1        2         9
2            1        4        10
3            1        3        12
4            1        6        17
..         ...      ...       ...
429         15       19         8
430         16       18         7
431         17       18         6
432         18       20        30
433         19       20        10

[434 rows x 3 columns]

In [74]:
# Đổi tên các cột
df = merged_df.rename(columns={"FromPoint": "StartPoint", "ToPoint": "EndPoint", "chieudai": "Distance"})

print(df)

     StartPoint  EndPoint  Distance
0             1         1         0
1             1         2         9
2             1         4        10
3             1         3        12
4             1         6        17
..          ...       ...       ...
429          15        19         8
430          16        18         7
431          17        18         6
432          18        20        30
433          19        20        10

[434 rows x 3 columns]

In [75]:
import os

# Đường dẫn đến thư mục
folder_path = r'C:/Users/ASUS/Downloads/rescue_station_project/scripts/test_demo/csv'

# Kiểm tra nếu thư mục không tồn tại, tạo mới
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Tạo đường dẫn đến file CSV trong thư mục
file_path = os.path.join(folder_path, 'network_distance.csv')

# Lưu dataframe thành file CSV
df.to_csv(file_path, index=False)

# Hiển thị kết quả
print("File CSV đã được lưu thành công vào thư mục:", folder_path)

File CSV đã được lưu thành công vào thư mục: C:/Users/ASUS/Downloads/rescue_station_project/scripts/test_demo/csv